### ISSUE TITLE
Task submission fails due to core-site.xml formatting error

### ISSUE THREAD

**Issue by willferreira** [Azure/aztk#269]
Submitting a task:

`aztk spark cluster submit --id <cluster> --name pythonpi pi.py`

causes the following error:

```
Caused by: org.xml.sax.SAXParseException; systemId: file:/home/spark-2.2.0-bin-hadoop2.7/conf/core-site.xml; lineNumber: 16; columnNumber: 5; The string "--" is not permitted within comments.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:150)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2480)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2468)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2539)
	... 28 more
```
The cluster was created by:

`aztk spark cluster create --id <cluster> --vm-size standard_a2 --size 2 --docker-repo aztk/python:spark2.2.0-python3.6.2-base`

**Comment by jafreck** [comment]
Did you modify the core-site.xml in your `.aztk` directory? Or did this error appear using the default core-site.xml (which is created after running `aztk spark init`)?

**Comment by willferreira** [comment]
My bad. I edited the local core-site.xml but introduced a typo. Should've looked there first, but was confused by file location in error message.

**Comment by jafreck** [comment]
No problem, glad to hear you got it working.
