### ISSUE TITLE
custom-script not initialising nltk

### ISSUE THREAD

**Issue by willferreira** [Azure/aztk#290]
I'm trying to initialise nltk on my worker nodes on cluster creation using a custom script `nltk_download.sh` which looks like this:
```

#! /bin/bash

python -c "import nltk; nltk.download('vader_lexicon')" > /dev/null
```
My cluster.yaml file looks like this:

```
# # optional custom scripts to run on the Spark master, Spark worker or all nodes in the cluster
custom_scripts: 
    - script: ./nltk_download.sh
      runOn: worker
```
The cluster is created without a problem, but when I run my python script on the cluster, which imports nltk, I get the following output:

```
17/12/19 15:35:59 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, 10.0.0.5, executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/spark-current/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/home/spark-current/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/home/spark-current/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/batch/workitems/wfspark03/job-1/factsettextextraction/wd/text_extraction.py", line 75, in <lambda>
  File "/batch/workitems/wfspark03/job-1/factsettextextraction/wd/text_extraction.py", line 26, in extract_transcript_text
  File "//.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/nltk/sentiment/vader.py", line 204, in __init__
    self.lexicon_file = nltk.data.load(lexicon_file)
  File "//.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/nltk/data.py", line 814, in load
    opened_resource = _open(resource_url)
  File "//.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/nltk/data.py", line 932, in _open
    return find(path_, path + ['']).open()
  File "//.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/nltk/data.py", line 653, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource
  'sentiment/vader_lexicon.zip/vader_lexicon/vader_lexicon.txt'
  not found.  Please use the NLTK Downloader to obtain the
  resource:  >>> nltk.download()
  Searched in:
    - '/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
```

The cluster file `startup/stderr.txt` contains the following output:

```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
```
How can I get `nltk.download('vader_lexicon')` to work on the worker nodes?

**Comment by jafreck** [comment]
Can you try running the script with `runOn: all-nodes` instead of `worker`? I believe this might be an issue related to the logic for running custom scripts on workers only.

**Comment by willferreira** [comment]
Running the script with `runOn`: all-nodes instead of `worker` gets around the bug.

**Comment by willferreira** [comment]
However, I now find that the above fix no longer works since last night. The custom script I supplied in cluster.yaml is copied over and run. See attached log files for more info.

[stdout.txt](https://github.com/Azure/aztk/files/1578818/stdout.txt)
[stderr.txt](https://github.com/Azure/aztk/files/1578820/stderr.txt)
[docker.log](https://github.com/Azure/aztk/files/1578821/docker.log)

**Comment by jafreck** [comment]
You are right, there is a race condition here. There is a PR out to fix this already - we will work to get it merged as soon as possible. In the meantime, if you just wait for a few moments before submitting your spark app that relies on completion of custom scripts, you should be fine.

I created another issue for this, #300.
