### ISSUE TITLE
Cannot access wasbs filesystem from submitted job

### ISSUE THREAD

**Issue by emlyn** [Azure/aztk#366]
When I run an application via job submission, it looks like the azure storage jars are not added to the classpath (I see `java.io.IOException: No FileSystem for scheme: wasbs`). I've tried adding them to the application's `jars:` key in job.yaml, but this doesn't help.
In the log output I also see:
```
Warning: Local jar /home/spark-current/jars/azure-storage-2.0.0.jar does not exist, skipping.
Warning: Local jar /home/spark-current/jars/hadoop-azure-2.7.3.jar does not exist, skipping.
Warning: Local jar /home/spark-current/jars/azure-data-lake-store-sdk-2.2.3.jar does not exist, skipping.
```
Followed by:
```
java.io.FileNotFoundException: Jar /home/spark-current/jars/azure-storage-2.0.0.jar not found
	at org.apache.spark.SparkContext.addJarFile$1(SparkContext.scala:1807)
	at org.apache.spark.SparkContext.addJar(SparkContext.scala:1833)
	at org.apache.spark.SparkContext$$anonfun$12.apply(SparkContext.scala:466)
	at org.apache.spark.SparkContext$$anonfun$12.apply(SparkContext.scala:466)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:466)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2509)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:909)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:901)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:901)
```
And similar for `hadoop-azure-2.7.3.jar`, `azure-data-lake-store-sdk-2.2.3.jar`.
Do I need to do something in the config to make this work, or is it a bug?

**Comment by jafreck** [comment]
I'm investigating this issue. You should not need to do anything in the config. This is likely a bug.
