### ISSUE TITLE
UnicodeDecodeError when uploading node scripts on Ubuntu in Docker

### ISSUE THREAD

**Issue by shtratos** [Azure/aztk#444]
When running AZTK client in Ubuntu 16.04 in Docker I get this error when creating the cluster:

```
|Traceback (most recent call last):
  File "/mnt/mesos/sandbox/sandbox/.virtualenvs/aztk/bin/aztk", line 11, in <module>
    load_entry_point('aztk', 'console_scripts', 'aztk')()
  File "/opt/aztk/aztk_cli/entrypoint.py", line 35, in main
    run_software(args)
  File "/opt/aztk/aztk_cli/entrypoint.py", line 63, in run_software
    func(args)
  File "/opt/aztk/aztk_cli/spark/endpoints/spark.py", line 31, in execute
    func(args)
  File "/opt/aztk/aztk_cli/spark/endpoints/cluster/cluster.py", line 81, in execute
    func(args)
  File "/opt/aztk/aztk_cli/spark/endpoints/cluster/cluster_create.py", line 79, in execute
    wait=wait
  File "/opt/aztk/aztk/spark/client.py", line 29, in create_cluster
    node_data = NodeData(cluster_conf).add_core().done()
  File "/opt/aztk/aztk/internal/cluster_data/node_data.py", line 34, in add_core
    self._add_node_scripts()
  File "/opt/aztk/aztk/internal/cluster_data/node_data.py", line 158, in _add_node_scripts
    self.add_dir(os.path.join(ROOT_PATH, NODE_SCRIPT_FOLDER), exclude=['*.pyc'])
  File "/opt/aztk/aztk/internal/cluster_data/node_data.py", line 75, in add_dir
    self.zipf.writestr(os.path.join(relative_folder, file), f.read().replace('\r\n', '\n'))
  File "/mnt/mesos/sandbox/sandbox/.virtualenvs/aztk/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2818: ordinal not in range(128)
```

This seems to come from the fact that files are open with default encoding:
https://github.com/Azure/aztk/blob/2bed496c398c7c3860ad62b1ce7d9fc14ee299bb/aztk/internal/cluster_data/node_data.py#L74

It should be like this:
```python
with io.open(os.path.join(base, file), 'r', encoding='UTF-8') as f:
```

The same issue occurs in other places where files are open.

There's a good discussion here on why encoding should always be specified when opening files:
https://github.com/docker-library/python/pull/5#issuecomment-50556812

Meanwhile, the workaround is to set default encoding to UTF-8:
```
export LANG=C.UTF-8
```

**Comment by jafreck** [comment]
Thanks for the tip!
