### ISSUE TITLE
Running into org.apache.spark.SparkException: addFile does not support local directories when not running local mode.

### ISSUE THREAD

**Issue by saroup** [Azure/aztk#495]
I've been using the sdk_example.py to submit an application to a cluster. Now I have change a bit the code to be more modular and hence I added more .py files. I'm my ApplicationConfiguration I added the path to the folder that contains the python modules that I have created through py_files argument.
(Note that I had to change the iteration over python files in generate_task in submit.py to be for py_file in os.listdir(application.py_files))

After adding the py_files and when I try to run my code using the sdk_example.py I get the following:
**18/04/18 21:30:49 ERROR SparkContext: Error initializing SparkContext.
org.apache.spark.SparkException: addFile does not support local directories when not running local mode.**
        at org.apache.spark.SparkContext.addFile(SparkContext.scala:1533)
        at org.apache.spark.SparkContext.addFile(SparkContext.scala:1503)
        at org.apache.spark.SparkContext$$anonfun$13.apply(SparkContext.scala:470)
        at org.apache.spark.SparkContext$$anonfun$13.apply(SparkContext.scala:470)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:470)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:236)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
18/04/18 21:30:49 INFO SparkUI: Stopped Spark web UI at http://10.0.0.6:4040
18/04/18 21:30:49 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
18/04/18 21:30:49 ERROR Utils: Uncaught exception in thread Thread-3
java.lang.NullPointerException
        at org.apache.spark.network.shuffle.ExternalShuffleClient.close(ExternalShuffleClient.java:141)
        at org.apache.spark.storage.BlockManager.stop(BlockManager.scala:1485)
        at org.apache.spark.SparkEnv.stop(SparkEnv.scala:90)
        at org.apache.spark.SparkContext$$anonfun$stop$11.apply$mcV$sp(SparkContext.scala:1937)
        at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1317)
        at org.apache.spark.SparkContext.stop(SparkContext.scala:1936)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:587)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:236)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
18/04/18 21:30:49 INFO SparkContext: Successfully stopped SparkContext
Traceback (most recent call last):
  File "/mnt/batch/tasks/workitems/loblawcluster148/job-1/loblaw_energyforcasting/wd/main_energyforcast.py", line 18, in <module>
    **spark = SparkSession.builder.enableHiveSupport().getOrCreate()**
  File "/home/spark-current/python/lib/pyspark.zip/pyspark/sql/session.py", line 169, in getOrCreate
  File "/home/spark-current/python/lib/pyspark.zip/pyspark/context.py", line 334, in getOrCreate
  File "/home/spark-current/python/lib/pyspark.zip/pyspark/context.py", line 118, in __init__
  File "/home/spark-current/python/lib/pyspark.zip/pyspark/context.py", line 180, in _do_init
  File "/home/spark-current/python/lib/pyspark.zip/pyspark/context.py", line 273, in _initialize_context
  File "/home/spark-current/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1401, in __call__
  File "/home/spark-current/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: addFile does not support local directories when not running local mode.
        at org.apache.spark.SparkContext.addFile(SparkContext.scala:1533)
        at org.apache.spark.SparkContext.addFile(SparkContext.scala:1503)
        at org.apache.spark.SparkContext$$anonfun$13.apply(SparkContext.scala:470)
        at org.apache.spark.SparkContext$$anonfun$13.apply(SparkContext.scala:470)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:470)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:236)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)

**Comment by jafreck** [comment]
I'm not sure I understand the steps you took to produce this result. You edited aztk code in submit.py to accept adding pyfiles by directory and now you are experiencing issues?

Can you lay out what you are intending to do and steps to reproduce the issue you are experiencing?

**Comment by saroup** [comment]
I created my own python files I then added the path to the folder that contains these files as a py_files in application configuration so that I can import them in my main app.
The reason I had to make a change in the submit.py so that it reads each file properly. That was a side note and my change worked as in it was able to identify each file in the folder I specified.
However, after adding the py_files I started getting this error.

I hope my explanation makes sense

**Comment by jafreck** [comment]
Okay, thanks for clarifying. Which Docker image are you using?

**Comment by saroup** [comment]
It looks like I was not inputing the file dependencies in the right way. It should look like this

app1 = aztk.spark.models.ApplicationConfiguration(
    name="myapp",
    application= os.path.join(ROOT_PATH, 'myapp.py'),
    driver_memory = "30g",
    executor_memory = "30g, 
    py_files =['module1.py', 'module2.py', 'module3.py']
)

**Comment by jafreck** [comment]
Thanks for the update. Was the issue resolved when you passed a list of the pyfiles?
