### ISSUE TITLE
msrest.exceptions.ValidationError: Parameter 'node_id' can not be None.

### ISSUE THREAD

**Issue by k-pratik** [Azure/aztk#511]
I am getting following error when submitting my spark job

```
Traceback (most recent call last):
  File "/usr/local/bin/aztk", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/aztk_cli/entrypoint.py", line 35, in main
    run_software(args)
  File "/usr/local/lib/python3.6/site-packages/aztk_cli/entrypoint.py", line 63, in run_software
    func(args)
  File "/usr/local/lib/python3.6/site-packages/aztk_cli/spark/endpoints/spark.py", line 31, in execute
    func(args)
  File "/usr/local/lib/python3.6/site-packages/aztk_cli/spark/endpoints/cluster/cluster.py", line 81, in execute
    func(args)
  File "/usr/local/lib/python3.6/site-packages/aztk_cli/spark/endpoints/cluster/cluster_submit.py", line 139, in execute
    wait=False
  File "/usr/local/lib/python3.6/site-packages/aztk/spark/client.py", line 92, in submit
    cluster_submit_helper.submit_application(self, cluster_id, application, wait)
  File "/usr/local/lib/python3.6/site-packages/aztk/spark/helpers/submit.py", line 116, in submit_application
    task = affinitize_task_to_master(spark_client, cluster_id, task)
  File "/usr/local/lib/python3.6/site-packages/aztk/spark/helpers/submit.py", line 106, in affinitize_task_to_master
    master_node = spark_client.batch_client.compute_node.get(pool_id=cluster_id, node_id=cluster.master_node_id)
  File "/usr/local/lib/python3.6/site-packages/azure/batch/operations/compute_node_operations.py", line 368, in get
    'nodeId': self._serialize.url("node_id", node_id, 'str')
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 488, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 558, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'node_id' can not be None.
```

```
aztk spark cluster list
Cluster                           | State     | VM Size             | Nodes  
----------------------------------|-----------|---------------------|-------
spark                             | active    | standard_a2         | 4        
```

I am submitting my job using following command

` aztk spark cluster submit --id spark --name mr101 /Users/kumar.pratik/test.jar --class com.kpratik.MainTest  `

Could you please let me know if I am missing something

**Comment by jafreck** [comment]
This error happens when the master has not yet been selected for the cluster. The error here is not good but it has already been fixed in #479 and will be included in the next release.
