### ISSUE TITLE
Error on creating cluster (Ubuntu DSVM)

### ISSUE THREAD

**Issue by revodavid** [Azure/aztk#542]
I can't seem to create a cluster using the Ubuntu DSVM using aztk 0.7.0. I get the errors below.

Pretty sure everything is set up as it should be. For example `aztk spark cluster list` completes successfully (and returns no clusters).

```
davidsmi@dms-dsvm1:~/sparkwd$ aztk spark cluster create --id dmsbuild7 --size 4
Traceback (most recent call last):
  File "/anaconda/envs/py35/bin/aztk", line 11, in <module>
    sys.exit(main())
  File "/anaconda/envs/py35/lib/python3.5/site-packages/aztk_cli/entrypoint.py", line 46, in main
    run_software(args)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/aztk_cli/entrypoint.py", line 75, in run_software
    func(args)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/aztk_cli/spark/endpoints/spark.py", line 32, in execute
    func(args)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/aztk_cli/spark/endpoints/cluster/cluster.py", line 87, in execute
    func(args)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/aztk_cli/spark/endpoints/cluster/cluster_create.py",line 38, in execute
    cluster_conf.spark_configuration = load_aztk_spark_config()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/aztk_cli/config.py", line 424, in load_aztk_spark_config
    core_site_xml=get_file_if_exists('core-site.xml'))
  File "/anaconda/envs/py35/lib/python3.5/site-packages/aztk/spark/models/models.py", line 61, in __init__
    self.ssh_key_pair = self.__generate_ssh_key_pair()
  File "/anaconda/envs/py35/lib/python3.5/site-packages/aztk/spark/models/models.py", line 66, in __generate_ssh_key_pair
    pub_key = key.publickey().exportKey('OpenSSH')
  File "/anaconda/envs/py35/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 352, in exportKey
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
  File "/anaconda/envs/py35/lib/python3.5/site-packages/Crypto/PublicKey/RSA.py", line 352, in <listcomp>
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
TypeError: can't concat str to bytes
```

**Comment by jafreck** [comment]
Is this error occuring on the WSL installation in #541?

It looks like these two might be related issue if so.

**Comment by revodavid** [comment]
Nope, this is on a stock Ubuntu install on the DSVM (my attempt to get around the WSL issue)
