### ISSUE TITLE
Azure Batch 500s retrieving logs cause jobs to fail

### ISSUE THREAD

**Issue by jaley** [Azure/aztk#555]
We're using `azure spark cluster submit ...` to run automated jobs from a VSTS release pipeline. Doing so means driver logs are streamed back to VSTS, which can be helpful for catching some of the simpler failure scenarios in one convenient place. 

Sometimes, however, the log streaming fails because of repeated 500s coming back from the Azure Batch requests:

```
2018-05-12T11:16:09.0168643Z Traceback (most recent call last):
2018-05-12T11:16:09.0183289Z   File "/usr/local/bin/aztk", line 11, in <module>
2018-05-12T11:16:09.0199649Z     load_entry_point('aztk', 'console_scripts', 'aztk')()
2018-05-12T11:16:09.0217199Z   File "/build/aztk/aztk_cli/entrypoint.py", line 46, in main
2018-05-12T11:16:09.0230599Z     run_software(args)
2018-05-12T11:16:09.0245738Z   File "/build/aztk/aztk_cli/entrypoint.py", line 75, in run_software
2018-05-12T11:16:09.0260288Z     func(args)
2018-05-12T11:16:09.0275944Z   File "/build/aztk/aztk_cli/spark/endpoints/spark.py", line 32, in execute
2018-05-12T11:16:09.0292820Z     func(args)
2018-05-12T11:16:09.0306941Z   File "/build/aztk/aztk_cli/spark/endpoints/cluster/cluster.py", line 87, in execute
2018-05-12T11:16:09.0321493Z     func(args)
2018-05-12T11:16:09.0336427Z   File "/build/aztk/aztk_cli/spark/endpoints/cluster/cluster_submit.py", line 154, in execute
2018-05-12T11:16:09.0351687Z     exit_code = utils.stream_logs(client=spark_client, cluster_id=args.cluster_id, application_name=args.name)
2018-05-12T11:16:09.0366758Z   File "/build/aztk/aztk_cli/utils.py", line 128, in stream_logs
2018-05-12T11:16:09.0381407Z     current_bytes=current_bytes)
2018-05-12T11:16:09.0396052Z   File "/build/aztk/aztk/spark/client.py", line 160, in get_application_log
2018-05-12T11:16:09.0411045Z     cluster_id, application_name, tail, current_bytes)
2018-05-12T11:16:09.0426059Z   File "/build/aztk/aztk/spark/helpers/get_log.py", line 75, in get_log
2018-05-12T11:16:09.0441027Z     file = __get_output_file_properties(batch_client, cluster_id, application_name)
2018-05-12T11:16:09.0457305Z   File "/build/aztk/aztk/spark/helpers/get_log.py", line 40, in __get_output_file_properties
2018-05-12T11:16:09.0471993Z     cluster_id, application_name, output_file, batch_client)
2018-05-12T11:16:09.0487103Z   File "/build/aztk/aztk/utils/helpers.py", line 334, in get_file_properties
2018-05-12T11:16:09.0501807Z     job_id, task_id, file_path, raw=True)
2018-05-12T11:16:09.0519066Z   File "/usr/local/lib/python3.5/dist-packages/azure/batch/operations/file_operations.py", line 337, in get_properties_from_task
2018-05-12T11:16:09.0537944Z     response = self._client.send(request, header_parameters, stream=False, **operation_config)
2018-05-12T11:16:09.0555444Z   File "/usr/local/lib/python3.5/dist-packages/msrest/service_client.py", line 290, in send
2018-05-12T11:16:09.0574367Z     raise_with_traceback(ClientRequestError, msg, err)
2018-05-12T11:16:09.0593205Z   File "/usr/local/lib/python3.5/dist-packages/msrest/exceptions.py", line 45, in raise_with_traceback
2018-05-12T11:16:09.0625508Z     raise error.with_traceback(exc_traceback)
2018-05-12T11:16:09.0643329Z   File "/usr/local/lib/python3.5/dist-packages/msrest/service_client.py", line 257, in send
2018-05-12T11:16:09.0660425Z     **kwargs)
2018-05-12T11:16:09.0677563Z   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
2018-05-12T11:16:09.0695719Z     resp = self.send(prep, **send_kwargs)
2018-05-12T11:16:09.0712193Z   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
2018-05-12T11:16:09.0730036Z     r = adapter.send(request, **kwargs)
2018-05-12T11:16:09.0746765Z   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 499, in send
2018-05-12T11:16:09.0765142Z     raise RetryError(e, request=request)
2018-05-12T11:16:09.0785601Z msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='<account>.northeurope.batch.azure.com', port=443): Max retries exceeded with url: /jobs/daily-1b90/tasks/daily/files/wd%2Foutput.log?api-version=2018-03-01.6.1 (Caused by ResponseError('too many 500 error responses',))
```

This causes the `submit` command to exit with a non-zero exit status. When that command exits, we tear down our cluster and fail the job if the code was non-zero, else pass. The fact that errors retrieving the logs due to temporary service outages are indistinguishable from job completion makes it hard to reliably operationalize aztk jobs right now.

**Comment by jafreck** [comment]
If I'm understanding you correctly, the issue is that the Batch service occasionally will respond with a series of 500 errors and error out. It seems like aztk should, in that case, error out as well with a non-zero exit code. Any retry logic to mitigate the impact of temporary service outages would need to come in your script.

I'm not sure I understand why this is indistinguishable from job completion. Job completion in the successful scenario will return with a 0 exit code. Is the issue about not having visibility into error states and logs?

**Comment by jaley** [comment]
Yeah, the issue is that I can't tell whether the job exited (successfully
or not) and therefore the correct client action is to shutdown the cluster,
or whether there was merely a problem retrieving the output logs and so I
should leave the cluster online (because the job is probably still running)
and flag this for manual cleanup later.
