### ISSUE TITLE
FileNotFoundError while ssh

### ISSUE THREAD

**Issue by kashifsayeed** [Azure/aztk#701]
-------------------------------------------
spark cluster id:              mitestclstr
open webui:                    http://localhost:8080
open jobui:                    http://localhost:4040
open jobhistoryui:             http://localhost:18080
ssh username:                  spark
connect:                       True
-------------------------------------------
Press ctrl+c to exit...
encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\aztk_cli\spark\endpoints\cluster\cluster_ssh.py", line 66, in execute
    shell_out_ssh(spark_client, cluster_configuration, ssh_conf)
  File "d:\anaconda\lib\site-packages\aztk_cli\spark\endpoints\cluster\cluster_ssh.py", line 140, in shell_out_ssh
    internal=ssh_conf.internal,
  File "d:\anaconda\lib\site-packages\aztk_cli\utils.py", line 167, in ssh_in_master
    subprocess.call(["ssh"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "d:\anaconda\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "d:\anaconda\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "d:\anaconda\lib\subprocess.py", line 993, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\Scripts\aztk.exe\__main__.py", line 9, in <module>
  File "d:\anaconda\lib\site-packages\aztk_cli\entrypoint.py", line 44, in main
    run_software(args)
  File "d:\anaconda\lib\site-packages\aztk_cli\entrypoint.py", line 72, in run_software
    func(args)
  File "d:\anaconda\lib\site-packages\aztk_cli\spark\endpoints\spark.py", line 25, in execute
    func(args)
  File "d:\anaconda\lib\site-packages\aztk_cli\spark\endpoints\cluster\cluster.py", line 76, in execute
    func(args)
  File "d:\anaconda\lib\site-packages\aztk_cli\spark\endpoints\cluster\cluster_ssh.py", line 69, in execute
    native_python_ssh_into_master(spark_client, cluster, cluster_configuration, ssh_conf, args.password)
  File "d:\anaconda\lib\site-packages\aztk_cli\spark\endpoints\cluster\cluster_ssh.py", line 124, in native_python_ssh_into_master
    internal=ssh_conf.internal,
  File "d:\anaconda\lib\site-packages\aztk\spark\client\cluster\operations.py", line 312, in ssh_into_master
    port_forward_list, internal)
  File "d:\anaconda\lib\site-packages\aztk\spark\client\cluster\helpers\ssh_into_master.py", line 20, in ssh_into_master
    port_forward_list, internal)
  File "d:\anaconda\lib\site-packages\aztk\client\base\base_operations.py", line 76, in ssh_into_node
    ssh_into_node.ssh_into_node(self, id, node_id, username, ssh_key, password, port_forward_list, internal)
  File "d:\anaconda\lib\site-packages\aztk\client\base\helpers\ssh_into_node.py", line 26, in ssh_into_node
    port_forward_list=port_forward_list,
  File "d:\anaconda\lib\site-packages\aztk\utils\ssh.py", line 279, in node_ssh
    hostname=hostname, port=port, username=username, password=password, pkey=ssh_key, timeout=timeout)
  File "d:\anaconda\lib\site-packages\aztk\utils\ssh.py", line 86, in connect
    client.connect(hostname, port=port, username=username, password=password, pkey=ssh_key, timeout=timeout)
  File "d:\anaconda\lib\site-packages\paramiko\client.py", line 437, in connect
    passphrase,
  File "d:\anaconda\lib\site-packages\paramiko\client.py", line 750, in _auth
    raise SSHException("No authentication methods available")
paramiko.ssh_exception.SSHException: No authentication methods available

**Comment by kashifsayeed** [comment]
The issue is resolved by passing the arguments by keywords instead of positional at line 107 on file cluster_ssh.py See  below
![image](https://user-images.githubusercontent.com/51479457/60565605-dcaa4880-9d81-11e9-862c-2d16c6ddf1b4.png)
