### ISSUE TITLE
issue while creating cluster

### ISSUE THREAD

**Issue by anit2** [Azure/aztk#705]
Im getting below error while im creating cluster. can anyone help. please

(bdp) (base) Anits-MacBook-Pro:.aztk agupta$ aztk spark cluster create --id mycluster --size 0 --size-low-priority 5 --vm-size standard_d12_v2
Traceback (most recent call last):
  File "/Users/agupta/bdpdev/bdp/bin/aztk", line 8, in <module>
    sys.exit(main())
  File "/Users/agupta/bdpdev/bdp/lib/python3.7/site-packages/aztk_cli/entrypoint.py", line 44, in main
    run_software(args)
  File "/Users/agupta/bdpdev/bdp/lib/python3.7/site-packages/aztk_cli/entrypoint.py", line 72, in run_software
    func(args)
  File "/Users/agupta/bdpdev/bdp/lib/python3.7/site-packages/aztk_cli/spark/endpoints/spark.py", line 25, in execute
    func(args)
  File "/Users/agupta/bdpdev/bdp/lib/python3.7/site-packages/aztk_cli/spark/endpoints/cluster/cluster.py", line 76, in execute
    func(args)
  File "/Users/agupta/bdpdev/bdp/lib/python3.7/site-packages/aztk_cli/spark/endpoints/cluster/cluster_create.py", line 36, in execute
    file_config, wait = config.read_cluster_config()
  File "/Users/agupta/bdpdev/bdp/lib/python3.7/site-packages/aztk_cli/config.py", line 55, in read_cluster_config
    return cluster_config_from_dict(config_dict)
  File "/Users/agupta/bdpdev/bdp/lib/python3.7/site-packages/aztk_cli/config.py", line 60, in cluster_config_from_dict
    if config.get("plugins") not in [[None], None]:
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by anit2** [comment]
there is a hidden folder access that  using ls -a in mac and you will have the out put

**Comment by yuvaldeg** [comment]
@anit2 , can you please explain more on how you were able to resolve the above? I'm getting the same exact issue
