### ISSUE TITLE
Error when setting up account

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/aztk#720]
I tried running account_setup; however, it had a Python error during run:

```
 …/tmp/spark  python3 account_setup.py

Getting credentials.
Multiple tenants detected. Please input the ID of the tenant you wish to use.
Tenants: /tenants/72f988bf-86f1-41af-91ab-2d7cd011db47, /tenants/17f57fb1-3a9e-4a8b-9521-db489c7594c0, /tenants/53ad779a-93e7-485c-ba20-ac8290d7252b, /tenants/ba7ce1c7-c6e7-4f24-a098-c18af62b23fb
Please input the ID of the tenant you wish to use: /tenants/72f988bf-86f1-41af-91ab-2d7cd011db47
Input the desired names and values for your Azure resources. Default values are provided in the brackets. Hit enter to use default.
Azure Region [westus]:
Resource Group Name [aztk]:
Storage Account Name [aztkstorage]: tmfaztkstorage
Batch Account Name [aztkbatch]: tmfaztkbatch
Active Directory Application Name [aztkapplication]: tmfaztkapplication
Active Directory Application Credential Name [aztk]: tmfaztk
Service Principal Name [aztksp]: tmfaztksp
Creating the Azure resources.
Created resource group.
Traceback (most recent call last):
  File "account_setup.py", line 369, in <module>
    storage_account_id = create_storage_account(creds, subscription_id, **kwargs)
  File "account_setup.py", line 84, in create_storage_account
    sku=Sku(SkuName.standard_lrs), kind=Kind.storage, location=kwargs.get('region', DefaultSettings.region)))
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by lastcoolnameleft** [comment]
Duplicate of https://github.com/Azure/aztk/issues/707
